### ISSUE TITLE
Can't edit job command. Only name and user.

### ISSUE THREAD

**Issue by Huron** [jamesrwhite/minicron#120]
![image](https://cloud.githubusercontent.com/assets/693433/7834994/0eeb430e-047e-11e5-80e3-98279f03e97d.png)

**Comment by jamesrwhite** [comment]
This is actually by design, the way jobs are stored does not allow the command to be edited because a hash of the command/host is used to identify the job.

**Comment by jamesrwhite** [comment]
Going to re-open this to serve as a reminder for something to investigate if it can be achieved in future versions.

**Comment by jamesrwhite** [comment]
Moment of inspiration, this is possible after all!

**Comment by jamesrwhite** [comment]
So https://github.com/jamesrwhite/minicron/commit/30f6db168739d6dbdb28be4b8ef26726f53ade0d makes this possible now with the caveat that this is a permanent change to the job so for example when you go back and look at an old execution it will be confusing now as it is tied to the latest copy of the job.

e.g

```
job 1 command = "echo 1"
job 1 execution 1 output = "1"
update job 1 command to = "echo 2"
go back and view job execution 1 and it now says the command is "echo 2" even though the output remains as "1"
```

I can think of a few different ways to handle this:

- Allow jobs to have multiple revisions (related to https://github.com/jamesrwhite/minicron/issues/68) and an execution will now be tied to a job revision instead of a job
- Embed the job details directly into what is saved for an execution instead of linking to the job

I don't really feel comfortable releasing this until this issue is resolved as it will no doubt lead to confusion. I'm open to any suggestions/thoughts on how to handle this?
