### ISSUE TITLE
Issue with default minicron.toml

### ISSUE THREAD

**Issue by cwhittl** [jamesrwhite/minicron#198]
When I copy it over to customize and restart I get Connection Refused with no error (even with debug and verbose enabled)

If I remove the file it goes back to normal.  

Any ideas?

**Comment by cwhittl** [comment]
I think I figured it out... I had to put the IP address I was accessing from in the server IP and it worked...  Not sure why it didn't work with 127.0.0.1 but it didn't

**Comment by jamesrwhite** [comment]
minicron uses that option to know what ip to listen on. If you put `127.0.0.1` as the server ip but access that server via `10.10.10.10` from the client it won't work because minicron isn't listening for traffic on `10.10.10.10`.

A common thing many people do in this situation is listen on `0.0.0.0` which effectively means all ip's if you need to access from more than one.
