### ISSUE TITLE
Cron task was scheduled as host user, not job user

### ISSUE THREAD

**Issue by Huron** [jamesrwhite/minicron#215]
User in host parameters is root. User in job parameters is www-data. But task was added into root's crontab.

minicron 0.9.2

**Comment by jamesrwhite** [comment]
Since `[v0.9.0](https://github.com/jamesrwhite/minicron/releases/tag/v0.9.0)` a job no longer has a user attcahed to it as it is now placed in the user crontab for the host user (see #180).

If you still want to replicate the previous behaviour of having a separate user for the job/user you use the `su` command to run your job as another user.

**Comment by jamesrwhite** [comment]
Closing this, feel free to re-open if you still have questions.
